package classes;
// Generated 07-jun-2018 11:59:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private String nombreCategoria;
     private Set noticias = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public Categoria(String nombreCategoria, Set noticias) {
       this.nombreCategoria = nombreCategoria;
       this.noticias = noticias;
    }
   
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }
    
    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }
    public Set getNoticias() {
        return this.noticias;
    }
    
    public void setNoticias(Set noticias) {
        this.noticias = noticias;
    }




}


