package classes;
// Generated 07-jun-2018 11:59:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private Integer idComentario;
     private Noticia noticia;
     private String nombreUsuario;
     private Integer idPadre;
     private Date fechaComentario;
     private String mensaje;

    public Comentario() {
    }

	
    public Comentario(Noticia noticia, String nombreUsuario, Date fechaComentario, String mensaje) {
        this.noticia = noticia;
        this.nombreUsuario = nombreUsuario;
        this.fechaComentario = fechaComentario;
        this.mensaje = mensaje;
    }
    public Comentario(Noticia noticia, String nombreUsuario, Integer idPadre, Date fechaComentario, String mensaje) {
       this.noticia = noticia;
       this.nombreUsuario = nombreUsuario;
       this.idPadre = idPadre;
       this.fechaComentario = fechaComentario;
       this.mensaje = mensaje;
    }
   
    public Integer getIdComentario() {
        return this.idComentario;
    }
    
    public void setIdComentario(Integer idComentario) {
        this.idComentario = idComentario;
    }
    public Noticia getNoticia() {
        return this.noticia;
    }
    
    public void setNoticia(Noticia noticia) {
        this.noticia = noticia;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public Integer getIdPadre() {
        return this.idPadre;
    }
    
    public void setIdPadre(Integer idPadre) {
        this.idPadre = idPadre;
    }
    public Date getFechaComentario() {
        return this.fechaComentario;
    }
    
    public void setFechaComentario(Date fechaComentario) {
        this.fechaComentario = fechaComentario;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }




}


