package classes;
// Generated 07-jun-2018 11:59:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Notificacion generated by hbm2java
 */
public class Notificacion  implements java.io.Serializable {


     private Integer idNotificacion;
     private Usuario usuario;
     private Date fechaNotifiacion;
     private String mensaje;

    public Notificacion() {
    }

    public Notificacion(Usuario usuario, Date fechaNotifiacion, String mensaje) {
       this.usuario = usuario;
       this.fechaNotifiacion = fechaNotifiacion;
       this.mensaje = mensaje;
    }
   
    public Integer getIdNotificacion() {
        return this.idNotificacion;
    }
    
    public void setIdNotificacion(Integer idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaNotifiacion() {
        return this.fechaNotifiacion;
    }
    
    public void setFechaNotifiacion(Date fechaNotifiacion) {
        this.fechaNotifiacion = fechaNotifiacion;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }




}


