package classes;
// Generated 07-jun-2018 11:59:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String nombreUsuario;
     private String password;
     private String nombreReal;
     private String email;
     private String localizacion;
     private String rol;
     private Set noticias = new HashSet(0);
     private Set historias = new HashSet(0);
     private Set notificacions = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nombreUsuario, String password, String nombreReal, String email, String localizacion, String rol) {
        this.nombreUsuario = nombreUsuario;
        this.password = password;
        this.nombreReal = nombreReal;
        this.email = email;
        this.localizacion = localizacion;
        this.rol = rol;
    }
    public Usuario(String nombreUsuario, String password, String nombreReal, String email, String localizacion, String rol, Set noticias, Set historias, Set notificacions) {
       this.nombreUsuario = nombreUsuario;
       this.password = password;
       this.nombreReal = nombreReal;
       this.email = email;
       this.localizacion = localizacion;
       this.rol = rol;
       this.noticias = noticias;
       this.historias = historias;
       this.notificacions = notificacions;
    }
   
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombreReal() {
        return this.nombreReal;
    }
    
    public void setNombreReal(String nombreReal) {
        this.nombreReal = nombreReal;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLocalizacion() {
        return this.localizacion;
    }
    
    public void setLocalizacion(String localizacion) {
        this.localizacion = localizacion;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Set getNoticias() {
        return this.noticias;
    }
    
    public void setNoticias(Set noticias) {
        this.noticias = noticias;
    }
    public Set getHistorias() {
        return this.historias;
    }
    
    public void setHistorias(Set historias) {
        this.historias = historias;
    }
    public Set getNotificacions() {
        return this.notificacions;
    }
    
    public void setNotificacions(Set notificacions) {
        this.notificacions = notificacions;
    }




}


